### Register
POST {{baseUrl}}/auth/register
Accept: application/json
Content-Type: application/json

{
  "username": "nathan-yan@email.com",
  "password": "senhasegura123",
  "name": "Nathan Yan",
  "document": "935.411.347-80",
  "phone": "(11) 99587-4754",
  "birthDate": "2001-05-01",
  "addresses": [
    {
      "street": "Rua Pindamonhangaba",
      "number": 333,
      "neighborhood": "Bairro Paraíso",
      "zipCode": "13200-000",
      "city": "Jundiaí",
      "state": "SP",
      "country": "Brasil",
      "isDefault": true
    }
  ]
}

> {%
    client.global.set("accessToken", response.body.token);
    client.global.set("refreshToken", response.body.refreshToken);
%}
