### Update Password
PATCH {{baseUrl}}/customers/me/password
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "currentPassword": "senhasegura123",
  "newPassword": "novasenha456",
  "confirmPassword": "novasenha456"
}

###
